/*
 * keyuser.h
 *
 *  Created on: Dec 24, 2021
 *      Author: zlf
 */

#ifndef KEYBOARD_KEYUSER_H_
#define KEYBOARD_KEYUSER_H_

#include "linux/input-event-codes.h"

#define USER_KEY_VALUE_FUNCTION_1	KEY_F1
#define USER_KEY_VALUE_FUNCTION_2	KEY_F3
#define USER_KEY_VALUE_FUNCTION_3	KEY_F5
#define USER_KEY_VALUE_FUNCTION_4	KEY_F7
#define USER_KEY_VALUE_FUNCTION_5	KEY_F9
#define USER_KEY_VALUE_FUNCTION_6	KEY_Z
#define USER_KEY_VALUE_FUNCTION_7	KEY_F2
#define USER_KEY_VALUE_FUNCTION_8	KEY_F4
#define USER_KEY_VALUE_FUNCTION_9	KEY_F6
#define USER_KEY_VALUE_FUNCTION_10	KEY_F8
#define USER_KEY_VALUE_FUNCTION_11	KEY_F10
#define USER_KEY_VALUE_FUNCTION_12	KEY_X

#define USER_KEY_VALUE_0			KEY_0
#define USER_KEY_VALUE_1			KEY_1
#define USER_KEY_VALUE_2			KEY_2
#define USER_KEY_VALUE_3			KEY_3
#define USER_KEY_VALUE_4			KEY_4
#define USER_KEY_VALUE_5			KEY_5
#define USER_KEY_VALUE_6			KEY_6
#define USER_KEY_VALUE_7			KEY_7
#define USER_KEY_VALUE_8			KEY_8
#define USER_KEY_VALUE_9			KEY_9
#define USER_KEY_VALUE_ASTERISK		KEY_KPASTERISK
#define USER_KEY_VALUE_POUND		KEY_KPSLASH

#define USER_KEY_VALUE_TELL				KEY_C
#define USER_KEY_VALUE_VOLUME_INCREASE	KEY_KPPLUS
#define USER_KEY_VALUE_VOLUME_DECREASE	KEY_MINUS

#define USER_KEY_VALUE_SWITCH		KEY_LEFTCTRL
#define USER_KEY_VALUE_INSIDE		KEY_F11
#define USER_KEY_VALUE_OUTSIDE		KEY_F12

#define USER_KEY_VALUE_UP			KEY_UP
#define USER_KEY_VALUE_DOWN			KEY_DOWN
#define USER_KEY_VALUE_PTT			KEY_P
#define USER_KEY_VALUE_LEFT			KEY_LEFT
#define USER_KEY_VALUE_RIGHT		KEY_RIGHT
#define USER_KEY_VALUE_OK			KEY_ENTER

/* Multi-keyboard only */
#define USER_KEY_VALUE_KEEP			KEY_H
#define USER_KEY_VALUE_SET			KEY_R
#define USER_KEY_VALUE_TEST			KEY_LEFTCTRL  //KEY_B  2023-02-09 改为leftctrl
/* Multi-keyboard only end */

#ifndef KEY_RED_LED
#define KEY_RED_LED		(0x28)
#endif
#ifndef KEY_GREEN_LED
#define KEY_GREEN_LED	(0x29)
#endif
#ifndef KEY_BLUE_LED
#define KEY_BLUE_LED	(0x2A)
#endif

#ifndef FRAME_CMD_TYPE_SET_BRIGHTNESS_MIN
#define FRAME_CMD_TYPE_SET_BRIGHTNESS_MIN	(0)
#endif
#ifndef FRAME_CMD_TYPE_SET_BRIGHTNESS_MAX
#define FRAME_CMD_TYPE_SET_BRIGHTNESS_MAX	(100)
#endif



#define BRIGHTNESS_RESPONSE_BIT 1   //获取亮度的响应位bit1
#define PANEL_MODEL_RESPONSE_BIT 2   //键盘类型的响应位bit2
#define PANEL_VER_RESPONSE_BIT 3   //键盘版本的响应位bit3
#define SET_BRIGHTNESS_RESPONSE_BIT 4   //设置亮度的响应位bit4
#define RESET_RESPONSE_BIT 5   //复位的响应位bit5
#define KEY_LED_ON_RESPONSE_BIT 6   //键灯点亮的响应位bit6
#define KEY_LED_OFF_RESPONSE_BIT 7   //键灯熄灭的响应位bit7
#define KEY_VALUE_REPLY_PRESS_RESPONSE_BIT 8   //xxx,按键按下的响应位bit8，这个不需要等响应，这个是主动读
#define KEY_VALUE_REPLY_RELEASE_RESPONSE_BIT 9   //xxx,按键松开的响应位bit9，这个不需要等响应，这个是主动读
#define KEY_LED_FLASH_RESPONSE_BIT 10   //闪烁键灯接口的响应位bit10







#endif /* KEYBOARD_KEYUSER_H_ */
